HOST: http://lahoda.info

--- Jackpot 3.0 Remoting API ---
---
Jackpot 3.0 Remoting API description
---

--
Basic resources
--
List all known indexes.
GET /index/list
> Accept: text/plain
< 200
< Content-Type: text/plain
jackpot30-remoting-example-data


List all classes with the given prefix.
GET /index/type/search?path=jackpot30-remoting-example-data&prefix=Class
> Accept: text/plain
< 200
< Content-Type: text/plain
{
    "example/src/": [
        "org.netbeans.modules.jackpot30.example.ClassA"
    ]
}

