HOST: http://lahoda.info

--- Jackpot 3.0 Remoting API ---
---
Jackpot 3.0 Remoting API description
---

--
Basic resources
--
List all known indexes.
GET /index/list
> Accept: text/plain
< 200
< Content-Type: text/plain
example


List all known indexes.
GET /index/symbol/search?path=netbeans-indexing&prefix=addImports
> Accept: text/plain
< 200
< Content-Type: text/plain
example

